# -*- coding: utf-8 -*-
"""Data_Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BOQXTC-Qm-ehf8TC8Fcj0a2qvuQCFfXC
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/GA/forest_data.csv')

columns_to_check = ['weather_conditions_over_fire', 'temperature', 'relative_humidity', 'wind_direction', 'wind_speed', 'fuel_type']

# Filter rows with non-null values in the specified columns
filtered_df = df[df[columns_to_check].notnull().all(axis=1)]

filtered_df.to_csv('/content/drive/My Drive/GA/filtered_data.csv', index=False)